# Generated by Django 3.0.9 on 2020-08-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': (('-date',),)},
        ),
        migrations.AlterModelTable(
            name='word',
            table='daily_words',
        ),
    ]
