# Generated by Django 3.0.9 on 2020-08-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20200827_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={},
        ),
    ]
