# Generated by Django 3.0.9 on 2020-08-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20200827_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='bgword',
            field=models.CharField(max_length=50, unique_for_date='date'),
        ),
    ]
