# Generated by Django 3.0.9 on 2020-08-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20200827_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='partOfSpeech',
            field=models.CharField(choices=[('n.', 'Noun'), ('adj.', 'Adjective'), ('v.', 'Verb'), ('adv.', 'Adverb')], default='n.', max_length=9),
        ),
    ]
